#!/usr/bin/env python3
"""Regenerate the favicon set from one geometry definition.

    python scripts/make-favicon.py

A one-off tool, deliberately not wired into `npm run build`: the icon changes
about never, and the build stays free of a Python dependency. Requires Pillow.

Why a generator rather than a hand-written SVG plus hand-drawn PNGs: the PNGs
are pure derivatives of the SVG, and keeping them in separate files is how the
raster fallback quietly stops matching the vector. Here both come from PATH
below, so they cannot disagree.

The mark is a square spiral - the Stein-Ulam-Wells display of 1964, which the
site is named after. Arm lengths grow 6.5, 6.5, 13, 13, 16.5, so it is a real
spiral rather than a decorative scroll, with the last arm truncated to keep a
margin. Only one and a half turns on purpose: a fuller spiral makes a better
picture and a worse icon, because at 16px the inner arms collapse into a
smudge. That was checked by rasterising to 16px and magnifying, not assumed.
"""
from PIL import Image, ImageDraw

UNITS = 32.0                      # design grid
BG = (20, 22, 26, 255)            # #14161a, the site's darkest background
FG = (122, 162, 247, 255)         # #7aa2f7, the dark theme's accent
STROKE = 2.8
TILE_RADIUS = 7.0
PATH = [(14.25, 16), (20.75, 16), (20.75, 9.5), (7.75, 9.5), (7.75, 22.5), (24.25, 22.5)]

# Supersample then downsample: Pillow has no antialiased drawing.
SS = 8


def render(px: int, radius: float) -> Image.Image:
    """The icon at `px` square. `radius` is the tile corner, in design units."""
    n = px * SS
    s = n / UNITS
    img = Image.new('RGBA', (n, n), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)
    if radius > 0:
        d.rounded_rectangle([0, 0, n - 1, n - 1], radius=radius * s, fill=BG)
    else:
        d.rectangle([0, 0, n - 1, n - 1], fill=BG)

    half = STROKE / 2 * s
    cap = STROKE / 2 * s  # stroke-linecap="square" extends the two open ends
    last = len(PATH) - 2
    for i in range(len(PATH) - 1):
        (x0, y0), (x1, y1) = PATH[i], PATH[i + 1]
        x0, y0, x1, y1 = x0 * s, y0 * s, x1 * s, y1 * s
        # Every segment is axis-aligned, so the union of expanded rectangles
        # gives exact miter joins without any join maths.
        if y0 == y1:
            if x1 < x0:
                x0, x1 = x1, x0
            if i == 0:
                x0 -= cap
            if i == last:
                x1 += cap
            box = [x0 - half, y0 - half, x1 + half, y1 + half]
        else:
            if y1 < y0:
                y0, y1 = y1, y0
            if i == 0:
                y0 -= cap
            if i == last:
                y1 += cap
            box = [x0 - half, y0 - half, x1 + half, y1 + half]
        d.rectangle(box, fill=FG)

    return img.resize((px, px), Image.LANCZOS)


def svg() -> str:
    d = f'M{PATH[0][0]} {PATH[0][1]}'
    for (x0, y0), (x1, y1) in zip(PATH, PATH[1:]):
        d += f' H{x1}' if y0 == y1 else f' V{y1}'
    return f'''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 32 32" role="img" aria-label="Ulam">
  <title>Ulam</title>
  <!-- Generated by scripts/make-favicon.py. Edit the geometry there, not here. -->
  <rect width="32" height="32" rx="{TILE_RADIUS:g}" fill="#14161a"/>
  <path d="{d}" fill="none" stroke="#7aa2f7" stroke-width="{STROKE:g}" stroke-linecap="square"/>
</svg>
'''


if __name__ == '__main__':
    with open('public/favicon.svg', 'w', encoding='utf-8', newline='\n') as f:
        f.write(svg())
    render(32, TILE_RADIUS).save('public/favicon-32.png')
    # Full bleed: iOS applies its own mask, so our rounded corners would show
    # as a dark halo inside Apple's smaller radius.
    render(180, 0).save('public/apple-touch-icon.png')
    print('wrote public/favicon.svg, favicon-32.png, apple-touch-icon.png')
